import "../styles/globals.scss";
import Head from "next/head";
import Link from "next/link";
import { parseCookies } from "nookies";

function MyApp({ Component, pageProps }) {
  const cookies = parseCookies();

  return (
    <div>
      <Head>
        <title>MiniLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href="/">
          <a>
            <h1>MiniLib</h1>
          </a>
        </Link>
      </nav>
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
